import {
  AutoServicesIcon,
  DomesticServicesIcon,
  EducationIcon,
  FinanceIcon,
  FitnessIcon,
  FlowersIcon,
  FoodIcon,
  ImmigrationIcon,
  ImmovablesIcon,
  InsuranceIcon,
  InternetIcon,
  LegalIcon,
  MedicineIcon,
  RelaxationIcon,
  ReligionIcon,
  ShopIcon,
  SportIcon,
  TourismIcon,
  TransportServicesIcon,
} from '../icons';

export const Categories = [
  { name: 'Еда', icon: FoodIcon },
  { name: 'Магазины', icon: ShopIcon },
  { name: 'Бытовые услуги', icon: DomesticServicesIcon },
  { name: 'Медицина', icon: MedicineIcon },
  { name: 'Красота и здоровье', icon: FitnessIcon },
  { name: 'Финансовые услуги', icon: FinanceIcon },
  { name: 'Автоуслуги', icon: AutoServicesIcon },
  { name: 'Транспортные услуги', icon: TransportServicesIcon },
  { name: 'Интернет и связь', icon: InternetIcon },
  { name: 'Туризм', icon: TourismIcon },
  { name: 'Операции с недвижимостью', icon: ImmovablesIcon },
  { name: 'Страхование', icon: InsuranceIcon },
  { name: 'Иммиграционные услуги', icon: ImmigrationIcon },
  { name: 'Юридические услуги', icon: LegalIcon },
  { name: 'Образование', icon: EducationIcon },
  { name: 'Спорт', icon: SportIcon },
  { name: 'Религия', icon: ReligionIcon },
  { name: 'Цветы и подарки', icon: FlowersIcon },
  { name: 'Развлечения и отдых', icon: RelaxationIcon },
];
